/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gotvednpnpkbcplurvvu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdHZlZG5wbnBrYmNwbHVydnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMTM4NTIsImV4cCI6MjA4Nzc4OTg1Mn0.0-wk0C06Nz_jbVmuhNEaFZfkcBlL-rJiOpEL48i2mkw"